<a href="https://colab.research.google.com/github/gcavalcantt/tag-classification/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Learning Project with Natural Language Processing (NLP)
This Machine Learning project focuses on multilabel classification, with the objective of applying this technique to classify tags in Stackoverflow questions. The project covers everything from the basic understanding of the multilabel classification concept to its practical implementation using the Scikit-Multilearn library.

# Setting Up The Environment
Importing dataset from Google Driver.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

Mounted at /content/drive


In [6]:
questions = pd.read_csv("/content/drive/MyDrive/Área de Estudos/Alura/Formações/Machine Learning para Negócios Digitais/database/stackoverflow_perguntas.csv")

In [7]:
questions.sample(10)

Perguntas          Tags
964   Estou desenvolvendo uma tela aonde tem um pass...          html
3544  estou usando o plugin owl-carousel 2.0.0, para...  jquery html 
256   O código abaixo retorna uma promessa:  CODE   ...        jquery
142   Estou pegando a lista assim:  CODE   Esse é me...       angular
3551  Tenho uma aplicação que esta apresentando um p...         html 
5192  Tenho um formulário que tem um botão de marcar...          html
1738  Galera tenho um plugin tooltip que funciona co...        jquery
4964  Preciso fazer o envio do formulário de um site...         html 
2721  Preciso passar uma variável do PHP em uma cláu...         html 
2563  Olá, estou estudando os Touch Events e fazendo...        jquery

In [8]:
print(len(questions))

5408


# Train and Test
Importing Scikit-learn and normalising the tags.

In [9]:
questions.Tags.unique()

array(['node.js', 'jquery', 'html', 'html angular ', 'html ', 'angular',
       'angular ', 'jquery html  ', 'jquery ', 'jquery html',
       'jquery html ', 'html angular', 'angular node.js ', 'html  ',
       'jquery html angular', 'node.js ', 'html jquery', 'html jquery ',
       'jquery angular  ', 'html node.js', 'jquery  ', 'angular node.js',
       'jquery angular', 'html node.js ', 'jquery node.js ', 'angular  ',
       'jquery angular ', 'jquery html angular ', 'node.js html ',
       ' node.js', 'node.js html', 'html angular  ', 'jquery node.js',
       'angular html', 'html angular  node.js', 'jquery html node.js',
       'html angular node.js'], dtype=object)

In [10]:
tag_list = list()
for tags in questions.Tags.unique():
    for tag in tags.split():
        if tag not in tag_list:
            tag_list.append(tag)

print(tag_list)

['node.js', 'jquery', 'html', 'angular']


In [11]:
node_js = list()
for tag_line in questions.Tags:
    if "node.js" in tag_line:
        node_js.append(1)
    else:
        node_js.append(0)
questions["node.js"] = node_js

questions

Perguntas           Tags  \
0     Possuo um projeto Node.js porém preciso criar ...        node.js   
1     Gostaria de fazer testes unitários no Node.js,...        node.js   
2     Como inverter a ordem com que o jQuery itera u...         jquery   
3     Eu tenho uma página onde pretendo utilizar um ...           html   
4     Como exibir os dados retornados do FireStore e...  html angular    
...                                                 ...            ...   
5403  Queria saber como pegar o total de cores de um...   jquery html    
5404  Boa noite, estou usando phonegap para fazer um...          html    
5405  Estou construindo um mini fórum, e nele, os us...    jquery html   
5406  Boa tarde,  Estou para desenvolver um site na ...           html   
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html   

      node.js  
0           1  
1           1  
2           0  
3           0  
4           0  
...       ...  
5403        0  
5404        0  
5405        0  
5406        0  
5407        0  

[5408 rows x 3 columns]

In [12]:
def new_column(tag_list, dataframe, tag_column_name):
    for tag in tag_list:
        column = list()
        for tag_line in dataframe[tag_column_name]:
            if tag in tag_line:
                column.append(1)
            else:
                column.append(0)
        dataframe[tag] = column

new_column(tag_list, questions, "Tags")
questions.sample(10)

Perguntas          Tags  \
1483  Estou tentando alterar um determinado valor de...        jquery   
2670  O projeto utiliza o Bootgrid para criar tabela...        jquery   
1103  Olá, pessoal.  Estou desenvolvendo uma página ...        html     
286   Estou perguntando isso pois a aplicação está q...   jquery html   
2440  Fala galera, estou com um probleminha aqui, de...        jquery   
4063  Uso WebSockets para meu projeto, no final fico...       node.js   
1296  Galera boa tarde.  Como faço uma função em jav...          html   
138   Estou comunicando meu site com a API do Behanc...      angular    
1748  No server-side tenho um serviço utilizando Spr...       angular   
5166  Observei que a página tem o seguinte código pa...  html angular   

      node.js  jquery  html  angular  
1483        0       1     0        0  
2670        0       1     0        0  
1103        0       0     1        0  
286         0       1     1        0  
2440        0       1     0        0  
4063        1       0     0        0  
1296        0       0     1        0  
138         0       0     0        1  
1748        0       0     0        1  
5166        0       0     1        1

In [15]:
from sklearn.model_selection import train_test_split

train_questions, test_questions, train_tags, test_tags = train_test_split(
    questions.Perguntas, # Questions
    questions.Tags
)

In [16]:
list_1 = [1, 2]
list_2 = [5, 4]
zipped_list = zip(list_1, list_2)
print(list(zipped_list))

[(1, 5), (2, 4)]


In [18]:
zipped_list_tags = list(zip(questions[tag_list[0]],
                            questions[tag_list[1]],
                            questions[tag_list[2]],
                            questions[tag_list[3]]))

questions["all_tags"] = zipped_list_tags
questions.sample(10)

Perguntas         Tags  node.js  \
1579  Olá, gostaria de mudar imagem e informações co...        html         0   
1716  Quero fazer um relacionamento entre duas "tabe...      angular        0   
635   Como encontro um efeito do tipo "parallax mous...       jquery        0   
3996  Tenho um botão onde eu posso adicionar campos ...       jquery        0   
4353  Tenho uma página com vários elementos estático...       jquery        0   
1678  Estou usando AngularJs e tenho esse método  CO...      angular        0   
286   Estou perguntando isso pois a aplicação está q...  jquery html        0   
1295  Estou com um servidor de telefonia Fortics.  A...      node.js        1   
1533  Tenho uma tabela no Google Drive e desejo usar...       jquery        0   
932   Boa tarde,  Vi vários exemplos na internet de ...       jquery        0   

      jquery  html  angular      all_tags  
1579       0     1        0  (0, 0, 1, 0)  
1716       0     0        1  (0, 0, 0, 1)  
635        1     0        0  (0, 1, 0, 0)  
3996       1     0        0  (0, 1, 0, 0)  
4353       1     0        0  (0, 1, 0, 0)  
1678       0     0        1  (0, 0, 0, 1)  
286        1     1        0  (0, 1, 1, 0)  
1295       0     0        0  (1, 0, 0, 0)  
1533       1     0        0  (0, 1, 0, 0)  
932        1     0        0  (0, 1, 0, 0)

In [19]:
tag_list

['node.js', 'jquery', 'html', 'angular']

In [21]:
train_questions, test_questions, train_tags, test_tags = train_test_split(
    questions.Perguntas, # Questions
    questions.all_tags,
    test_size = 0.2,
    random_state = 123
)

In [22]:
train_questions

1577       array1 = [1,2,3];   array2 = ["um","dois","...
1927    Não sei se fui claro no título, mas quem é da ...
3409    Alguém sabe me dizer qual a melhor forma de re...
4606    Estou com problemas ao tentar validar campos d...
5237    Preciso copiar um valor de dentro de um CODE  ...
                              ...                        
5218    Tenho um sisteminha, para mudar o layout da pá...
4060    Como fazer alto scoll ao carregar a página?  E...
1346    Explicação:  Tenho uma CODE  pai que contém du...
3454    Estou querendo fazer um sistema onde eu iria t...
3582    Galera eu to com um problemão, ja pesquisei ba...
Name: Perguntas, Length: 4326, dtype: object

# Vectorization

Applying TfidfVectorizer.

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000, max_df=0.85)
vectorizer

TfidfVectorizer(max_df=0.85, max_features=5000)

In [25]:
vectorizer.fit(questions.Perguntas) # Questions
train_questions_tfidf = vectorizer.transform(train_questions)
test_questions_tfidf = vectorizer.transform(test_questions)

print(train_questions_tfidf.shape)
print(test_questions_tfidf.shape)

(4326, 5000)
(1082, 5000)


# One-vs-Rest (OvR)
Also known as One-vs-All, it is a classification strategy where the multiclass problem is divided into multiple binary problems. For each class, a binary classifier is trained to distinguish whether a sample belongs to that class (with "rest" referring to all the other classes).

In [29]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np

In [31]:
# Binarizing the tags
mlb = MultiLabelBinarizer()
train_tags_binarized = mlb.fit_transform(train_tags)
test_tags_binarized = mlb.transform(test_tags)

In [32]:
# Training the classifier
logistic_regression = LogisticRegression()
onevsrest_classifier = OneVsRestClassifier(logistic_regression)
onevsrest_classifier.fit(train_questions_tfidf, train_tags_binarized)

/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:87: UserWarning: Label 0 is present in all training examples.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/multiclass.py:87: UserWarning: Label 1 is present in all training examples.
  warnings.warn(


OneVsRestClassifier(estimator=LogisticRegression())

In [33]:
train_tags_array = np.asarray(list(train_tags))
test_tags_array = np.asarray(list(test_tags))

In [34]:
train_tags_array

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       ...,
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 0]])

In [35]:
type(train_tags)

pandas.core.series.Series

In [36]:
train_tags_array = np.asarray(list(train_tags))
test_tags_array = np.asarray(list(test_tags))

print(train_tags_array)
print(type(train_tags_array))

[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]
<class 'numpy.ndarray'>


In [37]:
logistic_regression = LogisticRegression(solver = 'lbfgs')
onevsrest_classifier = OneVsRestClassifier(logistic_regression)
onevsrest_classifier.fit(train_questions_tfidf, train_tags_array)
onevsrest_result = onevsrest_classifier.score(test_questions_tfidf, test_tags_array)

print("Result: {0:.2f}%".format(onevsrest_result * 100))

Result: 41.87%


In [38]:
questions.all_tags.unique()

array([(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 1, 1),
       (0, 0, 0, 1), (0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 1, 1),
       (0, 1, 0, 1), (1, 0, 1, 0), (1, 1, 0, 0), (1, 0, 1, 1),
       (1, 1, 1, 0)], dtype=object)

In [39]:
len(questions.all_tags.unique())

13

In [40]:
1/13

0.07692307692307693

# Hamming Loss
A metric used to evaluate the performance of multilabel classification models. It measures the fraction of incorrectly predicted labels relative to the total number of labels.

In [41]:
from sklearn.metrics import hamming_loss

onevsrest_prediction = onevsrest_classifier.predict(test_questions_tfidf)
hamming_loss_onevsrest = hamming_loss(test_tags_array, onevsrest_prediction)

print("Hamming Loss: {0:.2f}".format(hamming_loss_onevsrest))

Hamming Loss: 0.19


In [43]:
# Selects only numeric columns
numeric_questions = questions.select_dtypes(include=['number'])

# Calculates the correlation between the numeric columns
correlation_matrix = numeric_questions.corr()
print(correlation_matrix)

          node.js    jquery      html   angular
node.js  1.000000 -0.321485 -0.273523 -0.101787
jquery  -0.321485  1.000000 -0.253977 -0.366269
html    -0.273523 -0.253977  1.000000 -0.286706
angular -0.101787 -0.366269 -0.286706  1.000000


# Multilabel Classification
Performing the final trainings and checking predictive results.

In [44]:
!pip install scikit-multilearn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB 2.6 MB/s eta 0:00:00


In [52]:
from skmultilearn.problem_transform import ClassifierChain
from skmultilearn.problem_transform import BinaryRelevance
from skmultilearn.adapt import MLkNN

In [48]:
# Initializing the ClassifierChain with logistic regression
chain_classifier = ClassifierChain(logistic_regression)

# Training the classifier
chain_classifier.fit(train_questions_tfidf, train_tags_array)

# Evaluating the model
chain_result = chain_classifier.score(test_questions_tfidf, test_tags_array)
chain_prediction = chain_classifier.predict(test_questions_tfidf)
chain_hamming_loss = hamming_loss(test_tags_array, chain_prediction)

print("Hamming Loss: {0:.2f}".format(chain_hamming_loss))
print("Result: {0:.2f}%".format(chain_result * 100))

Hamming Loss: 0.21
Result: 49.72%


In [49]:
# Initializing the BinaryRelevance with logistic regression
br_classifier = BinaryRelevance(logistic_regression)

# Training the binariser
br_classifier.fit(train_questions_tfidf, train_tags_array)

# Evaluating the model
br_result = br_classifier.score(test_questions_tfidf, test_tags_array)
br_prediction = br_classifier.predict(test_questions_tfidf)
br_hamming_loss = hamming_loss(test_tags_array, br_prediction)

print("Hamming Loss: {0:.2f}".format(br_hamming_loss))
print("Result: {0:.2f}%".format(br_result * 100))

Hamming Loss: 0.19
Result: 41.87%


In [56]:
classification_results = pd.DataFrame()

# Creating columns for the result models
classification_results["questions"] = test_questions.values
classification_results["actual tags"] = list(test_tags)
classification_results["BR"] = list(br_prediction.toarray())
classification_results["chain"] = list(chain_prediction.toarray())

classification_results

questions   actual tags  \
0     estou com conflito entre o  CODE   e os  CODE ...  (0, 1, 0, 0)   
1     Estou fazendo um site que eu sou obrigado a us...  (0, 0, 1, 0)   
2     Recentemente fiz um refactor do meu código par...  (1, 0, 0, 0)   
3     Eu tenho esse código em CODE  que passo valore...  (0, 1, 1, 0)   
4     Olá, em minha função tem o evento CODE  que de...  (0, 1, 1, 0)   
...                                                 ...           ...   
1077  Estou a desenvolver um website em jQuery. E at...  (0, 1, 0, 0)   
1078  Estou usando este plugin - jquery autocomplete...  (0, 1, 0, 0)   
1079  Tenho o seguinte jQuery:  CODE   Nisto, quanti...  (0, 1, 0, 0)   
1080  Estou usando o SimpleModal Contact Form de Eri...  (0, 1, 0, 0)   
1081  Estou tento problemas com o webpack, gostaria ...  (0, 0, 0, 1)   

                BR                 chain  
0     [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  
1     [0, 0, 1, 0]  [0.0, 0.0, 1.0, 0.0]  
2     [1, 0, 0, 0]  [1.0, 0.0, 0.0, 0.0]  
3     [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  
4     [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  
...            ...                   ...  
1077  [0, 1, 1, 0]  [0.0, 1.0, 1.0, 0.0]  
1078  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  
1079  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  
1080  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  
1081  [0, 0, 0, 0]  [0.0, 0.0, 1.0, 0.0]  

[1082 rows x 4 columns]

In [57]:
br_prediction

<1082x4 sparse matrix of type '<class 'numpy.int64'>'
	with 964 stored elements in Compressed Sparse Column format>

In [58]:
classification_results.iloc[1]

questions      Estou fazendo um site que eu sou obrigado a us...
actual tags                                         (0, 0, 1, 0)
BR                                                  [0, 0, 1, 0]
chain                                       [0.0, 0.0, 1.0, 0.0]
Name: 1, dtype: object

In this specific case, both the BinaryRelevance and ClassifierChain classifiers made the correct prediction for this question, correctly identifying the third tag as true (or active). This suggests that, for this instance, both multilabel classification models performed well.

If this pattern of accuracy continues across other instances, it would indicate that the models are well-tuned for the tags associated with the questions in the dataset.

In [59]:
classification_results.questions[1]

'Estou fazendo um site que eu sou obrigado a usar HTML, CSS e JavaScript no máximo. Só que muitas coisas que eu preciso do PhP eu não posso usar. Sendo assim eu estive pesquisando por sinonimo de CODE  e encontrei o seguinte, que ajudou em partes:  CODE   Tá, mas qual é o problema? Ele cria uma barra de rolagem do lado. Eu sei como remover com CSS, mas o texto que foi inserido rola só dentro da área da CODE  e eu queria que fizesse como se o texto inserido fizesse parte da página, como funciona no CODE  do PhP. A questão é, como fazer a mecânica do JavaScript nesse caso ficar igual ao do PhP?  Print para exemplificar: https://imgur.com/a/V9AGLgB '

**Translation**:

"*I am creating a website where I am required to use only HTML, CSS, and JavaScript. However, there are many things I need from PHP that I can't use. So, I have been researching alternatives for CODE and found the following, which partially helped: CODE.*

*Okay, but what's the problem? It creates a scrollbar on the side. I know how to remove it with CSS, but the inserted text scrolls only within the CODE area, and I want it to behave as if the inserted text is part of the page, similar to how it works in PHP CODE. The question is, how can I make the JavaScript mechanism in this case behave the same as in PHP?*

*Screenshot to illustrate:* https://imgur.com/a/V9AGLgB "